site_name: SOC-GHTK
theme: readthedocs

site_name: GHTK-SOC
theme: readthedocs
repo_url: https://github.com/ducna96/SOC-GHTK

markdown_extensions:
  - admonition

nav:
- installation:
  - Install install-graylog: installation/install-graylog.md
  - Install install-logtash-filebeat: installation/install-ELK.md
  - Install install-grafana-prometheus: installation/install-grafana-prometheus.md
- integration:
  - Configuration: integration/integration.md
