site_name: SOC-GHTK
theme: readthedocs

site_name: GHTK-SOC
theme: readthedocs
repo_url: https://github.com/ducna96/SOC-GHTK
edit_uri: https://github.com/ducna96/SOC-GHTK/edit/master/docs/
docs_dir: docs/
markdown_extensions:
  - admonition

nav:
- Introduction:
  - Welcome to GHTK-SOC: index.md
- installation:
  - Install install-Graylog: installation/install-Graylog.md
  - Install install-ELK: installation/install-ELK.md
  - Install install-Fleetdm-Osquery: installation/install-Fleetdm-Osquery.md
  - Install install-Sysmon-Winlogbeat: installation/install-Sysmon-Winlogbeat.md
  - Install install-Grafana-Prometheus: installation/install-Grafana-Prometheus.md
  - Install install-Suricata: installation/install-Suricata.md  
- integration:
  - Configuration: integration/integration.md
